app:
  name: ""
  component-name: ""
  description: ""
  version: "1.0"
  baseApiVersion: "4.0.0"
  schemaVersion: "1"
log:
  detail:
    level: "debug"
    enable-file-logging: true
    log-file-properties:
      dirname: "logs/detail"
      filename: "detail-%DATE%"
      date-pattern: "YYYY-MM-DD-HH"
      extension: ".log"
  summary:
    level: "info"
    enable-file-logging: false
    log-file-properties:
      dirname: "logs/summary"
      filename: "summary-%DATE%"
      date-pattern: "YYYY-MM-DD-HH"
      extension: ".log"