package logger

const (
	NORMAL         = "NORMAL"
	NOTICE         = "NOTICE"
	MINOR_ISSUE    = "MINOR_ISSUE"
	MAJOR_ISSUE    = "MAJOR_ISSUE"
	CRITICAL_ISSUE = "CRITICAL_ISSUE"
	SYSTEM_DOWN    = "SYSTEM_DOWN"
)

const (
	HEALTHY        = "HEALTHY"
	CLIENT_ERROR   = "CLIENT_ERROR"
	SYSTEM_ERROR   = "SYSTEM_ERROR"
	BUSINESS_ERROR = "BUSINESS_ERROR"
)
