services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.2
    container_name: filebeat
    # user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../user-service/logs:/app/user-service/logs:ro
      - ../product-service/logs:/app/product-service/logs:ro
      - ../order-service/logs:/app/order-service/logs:ro
    environment:
      - KAFKA_HOST=kafka:9092
    networks:
      - ms-service

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.2
    container_name: logstash
    ports:
      - '5044:5044'
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - KAFKA_HOST=kafka:9092
    depends_on:
      - elasticsearch
    networks:
      - ms-service

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - ms-service

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - ms-service
networks:
  ms-service:
    name: ms-service