services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - ENV=docker
      - DB_HOST=postgres
    volumes:
      - ./product-service/logs:/logs
    ports:
      - 8082:8082
    networks:
      - ms-service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - ENV=docker
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./user-service/logs:/logs
    ports:
      - 8080:8080
    networks:
      - ms-service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    restart: always
    environment:
      # - CONFIG_PATH=configs/.docker.env
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI=mongodb://mongo:27017
      - USER_SERVICE_URL=http://user-service:8080
      - PRODUCT_SERVICE_URL=http://product-service:8082
    volumes:
      - ./order-service/logs:/logs
    ports:
      - 8083:8083
    networks:
      - ms-service
networks:
  ms-service:
    name: ms-service
