# 🌐 NodePort Service สำหรับ client นอก cluster
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ms-service
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30092
  selector:
    app: kafka
---
# 🌀 Headless Service สำหรับ StatefulSet ภายใน cluster
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: ms-service
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: broker
  selector:
    app: kafka
---
# 🏗️ Kafka StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: ms-service
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.5
          ports:
            - containerPort: 9092
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.ms-service.svc.cluster.local:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT_INTERNAL
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:9093
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
          command:
            - sh
            - -c
            - |
              export KAFKA_BROKER_ID=$(echo $HOSTNAME | awk -F'-' '{print $NF}')
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://$(hostname -i):9092,PLAINTEXT_INTERNAL://$HOSTNAME.kafka-headless.ms-service.svc.cluster.local:9093"
              echo "Broker ID is $KAFKA_BROKER_ID"
              echo "Advertised listeners: $KAFKA_ADVERTISED_LISTENERS"
              exec /opt/bitnami/scripts/kafka/entrypoint.sh /run.sh
          volumeMounts:
            - name: datadir
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
