kubectl create namespace ms-service
kubectl apply -f zookeeper.yaml
kubectl apply -f kafka.yaml
kubectl apply -f kafka-ui.yaml


kubectl port-forward svc/kafka 9092:9092 -n ms-service &
kubectl port-forward svc/kafka-ui 8080:8080 -n ms-service