@uti=http://localhost:8083

POST {{uti}}/orders HTTP/1.1
Content-Type: application/json

{
    "customer_id": "0197b9c6-a3ca-7ea2-bf4e-a6c9ec2af1d8",
    "status": "pending",
    "items": [
        {
            "id": "07952a46-3110-406a-90d8-8723414068ed",
            "name": "p1",
            "quantity": 1,
            "price": 20.0
        }
    ],
    "total_price": 40.0
}