@uti=http://localhost:8083

POST {{uti}}/orders HTTP/1.1
Content-Type: application/json

{
    "customer_id": "0197d874-3325-7c6d-96c1-bf3953a4b5cf",
    "status": "pending",
    "items": [
        {
            "id": "7d57af1d-573d-48d1-affe-41fd79459c71",
            "name": "p1",
            "quantity": 1,
            "price": 20.0
        }
    ],
    "total_price": 40.0
}

###
GET http://localhost:8083/healthz HTTP/1.1