@uti=http://localhost:8083

POST {{uti}}/orders HTTP/1.1
Content-Type: application/json

{
    "customer_id": "0197d828-cfa5-7ac9-85de-e9dc4d2c3541",
    "status": "pending",
    "items": [
        {
            "id": "c8f809ad-0cf4-4825-937f-7e39ddf1e6cd",
            "name": "p1",
            "quantity": 1,
            "price": 20.0
        }
    ],
    "total_price": 40.0
}

###
GET http://localhost:8083/healthz HTTP/1.1